### ISSUE TITLE
Undefine a Type via Type Page

### ISSUE THREAD

**Issue by jmsfltchr** [vaticle/typedb-studio#115]
## Problem to Solve

There is no way to `undefine` Types that is visible to the user by default.

## Current Workaround

Currently Types can be undefined by right-clicking on the Type and choosing `delete` from the context menu.

## Proposed Solution

There are controls for modification of a Type available in the Concept Info sidebar panel. Therefore, this seems like the natural place to add an option to `undefine`.

## Additional Information

--

**Comment by jamesreprise** [comment]
Closed by the recent introduction of the schema editor!
