### ISSUE TITLE
Relations Labels

### ISSUE THREAD

**Issue by kristall** [vaticle/typedb-studio#117]
## Problem to Solve

![image](https://user-images.githubusercontent.com/643877/55442398-b2909100-55ae-11e9-8db7-028f0d79f8e2.png)

As you can see in the picture at the moment it is not really possible to make an relation show its own label and the only one relation can be chosen to display role labels. It would be a big improvement if one could choose with labels should be shown (especially on multiple roles from multiple relations), also the label of the relation type itself.

## Current Workaround

At the moment no real workaround. 

## Proposed Solution

Provide better options for relation label management.

**Comment by alexjpwalker** [comment]
Thanks for your report!

We have moved from Workbase to Studio. In Studio (and indeed in later versions of Workbase), relation labels are always visible.
