### ISSUE TITLE
Add export schema buttons to manage databases dialog

### ISSUE THREAD

**Issue by Irtazaraza** [vaticle/typedb-studio#119]
## Problem to Solve
Designing a schema on workbase does not persist the schema in any file and is only contained in the keyspace.

## Current Workaround
Write matching schema manually.

## Proposed Solution
Have a button to export the schema designed by workbase.

## Additional Information
N/A

**Comment by alexjpwalker** [comment]
This is now possible in TypeDB Studio! This issue is tracked at:
- #424

**Comment by alexjpwalker** [comment]
There is now a better workaround in TypeDB 2.0: Console has the ability to export the schema of the current database.

Having said that, it would be useful to be able to export the database schema from Studio while it is being built.

**Comment by jamesreprise** [comment]
Some of this functionality exists within Studio - but we want to be able to export schemas for the databases within the 'Manage Databases' dialog.
