### ISSUE TITLE
Infinite graph jumbling

### ISSUE THREAD

**Issue by BFergerson** [vaticle/typedb-studio#129]
## Description

The Grakn Workbase can be made to produce a graph which it will never make stationary.

Example:
![infinite_jumble3](https://user-images.githubusercontent.com/3278877/55770166-970b0780-5a40-11e9-935c-4b92aca5f913.gif)

## Environment

1. OS (where Grakn server runs): Ubuntu 18.04
2. Grakn version (and platform): Grakn Core 1.5
3. Grakn client: Grakn Workbase 1.2.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
```
Start Grakn 1.5

Load these files into Grakn:
 - https://github.com/CodeBrig/OmniSRC/tree/grakn-1.5-upgrade/src/test/resources/schema/segment_same/Actual_Roles.gql
 - https://github.com/CodeBrig/OmniSRC/tree/grakn-1.5-upgrade/src/test/resources/schema/segment_same/Base_Structure.gql
 - https://github.com/CodeBrig/OmniSRC/tree/grakn-1.5-upgrade/src/test/resources/schema/segment_same/Individual_Roles.gql

Open Grakn Workbase 1.2
Switch to schema editor mode, click "Entity Type"
```

## Expected Output

Graph should load and settle on an appropriate structure.

## Actual Output

Graph continuously moves around without ever becoming stationary.
 
## Additional information

I don't think this issue came from Grakn 1.5 or Grakn Workbase 1.2.0. I've seen the issue happen in many versions of Grakn. This is the smallest schema I've ever produced it with (~2k lines of Graql).

**Comment by Irtazaraza** [comment]
Hi @BFergerson 
Thanks for pointing it out. We are aware of this and will be working on fixing this. :)

**Comment by Irtazaraza** [comment]
[NOTE]: A current workaround is arranging the nodes by dragging them when the schema is loaded initially. This will store the node positions and next time you visualise the schema, the nodes will be at the positions you dragged them to. It can be made easier by hiding some of the types in the display settings panel in the right bar.

**Comment by sorsaffari** [comment]
Let's use Brandon's mega schema (https://github.com/CodeBrig/Arthur/blob/master/src/main/resources/schema/omnilingual/Arthur_Omnilingual_Base_Structure.gql) to reproduce this bug

**Comment by alexjpwalker** [comment]
We have moved from Workbase to Studio. Studio fixes this issue by having all node movement based on a force simulation, where the displacement at each iteration is multiplied by a value in the range [0..1] called **alpha**, and at each iteration, we multiply **alpha** by a value in the range (0..1) named **alphaDecay**.

This causes the value of **alpha** to drop at each iteration. When it drops below a certain threshold, named **alphaMin**, we stop the simulation.
