### ISSUE TITLE
English to Graql rules specification

### ISSUE THREAD

**Issue by neomatrix369** [vaticle/typedb-studio#153]
## Problem to Solve

Graql is a good language but it still can be a bit foreign with a bit of learning curve to non-programmers or programmers turned management personnel. It's easier for us to express what we want in English, hence a translator or a helper module could be beneficial to new and existing clients.

## Current Workaround

Using Graql and manually translating the English requirements to Graql.

## Proposed Solution

The translator is a helper and does not have to successful 100% in translating English sentences into Graql spec. The least it should do is present a template filling in most if not all of the entities from the English query into its Graql equivalent.

If presented via GUI, it can be further enhanced to help map the sentences and components of it into the Grakn entities and Graql language constructs. Two-Way reverse engineering would be an awesome topping on the cake. 

Saving a template of such mappings between English queries and Grakn and then making them available to end-users can improve productivity massively.

## Additional Information

@tomassabat tells me mauna.ai is busy working with something similar, although we do not know if they will publish an open source version of this work. 

Looking at Graql its not far away from English hence the mapping and translations can be done fluently.

**Comment by alexjpwalker** [comment]
Migrated to https://github.com/vaticle/docs/issues/573 .
