### ISSUE TITLE
Cancel a query

### ISSUE THREAD

**Issue by Irtazaraza** [vaticle/typedb-studio#156]
## Problem to Solve
User might want to cancel the queries that take too long to execute

## Current Workaround
User had to refresh workbase

## Proposed Solution
Button to close the transaction

## Additional Information
N/A

**Comment by alexjpwalker** [comment]
We essentially have this now with the ability to close the currently-running Transaction. Right, @haikalpribadi ?

**Comment by haikalpribadi** [comment]
We can either send a "stop signal", which will cancel the query after the "next response", or close the transaction which will terminate any running query immediately.
