### ISSUE TITLE
Hiding nodes leads to nodes floating away

### ISSUE THREAD

**Issue by BFergerson** [vaticle/typedb-studio#164]
## Description

When I hide nodes this leads to nodes floating away like this:
![hide-stuff](https://user-images.githubusercontent.com/3278877/61601334-24d6c100-abf2-11e9-8904-9a7ba6e36ba5.gif)

## Environment

1. Grakn version: Grakn Core 1.5.7
2. OS of Grakn server: Ubuntu 18.04
3. Workbase version: 1.2.2
4. OS of Workbase: Ubuntu 18.04

## Reproducible Steps

1. Pull a lot of nodes up
2. Hide nodes

## Expected Output

I would expect stuff not to float away

## Actual Output

Stuff floats away

**Comment by alexjpwalker** [comment]
I almost want to intentionally write this bug in Studio now, it's beautiful.

We've replaced Workbase with Studio. I assume... nodes don't float away by themselves now.
