### ISSUE TITLE
Schema Designer: The inherited attribute and role edges should be hidden by default and displayed on demand

### ISSUE THREAD

**Issue by sorsaffari** [vaticle/typedb-studio#167]
## Problem to Solve

Visualising a schema that heavily makes use of type hierarchies, clutters the visualiser as the edges between concepts _include_ those made to inherited `attribute`s and `role`s.

## Current Workaround

Leave the Schema Designer to query a subset of the schema in the Query Visualiser.

## Proposed Solution

Hide the inherited edges by default and allow the user to toggle them back on via an option in display settings. When displayed, inherited edges are drawn out using dashed lines to differentiate them from the non-inherited edges.

## Additional Information
N/A

**Comment by alexjpwalker** [comment]
We are no longer maintaining the Schema Designer in Workbase and have moved over to Studio so this issue is no longer relevant.
