### ISSUE TITLE
Query Visualiser: Provide UI feedback when no results found

### ISSUE THREAD

**Issue by sorsaffari** [vaticle/typedb-studio#175]
## Problem to Solve
When a query returns no answer, no UI feedback is provided.

## Current Workaround
Come to realise there is in fact no answer to the query.

## Proposed Solution
Use the `notifyInfo` to display an informative message.

## Additional Information
n/a

**Comment by alexjpwalker** [comment]
Log now prints `## Result> Match query did not match any concepts in the database.` We should re-test, once we have Graph output, that the user always gets some visual confirmation that no results were matched, even if they don't have the Log output open.

**Comment by jamesreprise** [comment]
Running a query that matches no concepts in the database always opens a run window with a log output with the text: 
`## Result> Match query did not match any concepts in the database.`

This is the case if no log output is open or if the run window is minimised or if there was previously a graph output.

This seems clear but we should re-open if we hear of this being a source of confusion.
