### ISSUE TITLE
Rewrite the UPDATE_METATYPE_INSTANCES to be an integration test

### ISSUE THREAD

**Issue by sorsaffari** [vaticle/typedb-studio#182]
The `UPDATE_METATYPE_INSTANCES` test located at `/test/unit/components/ScehmaDesign/store/actions.test.js` is, in fact, an integration test that relies on the answers retrieved by running a series of Graql queries on the `genealogy` keyspace of a running Grakn server.

**Comment by alexjpwalker** [comment]
This is no longer relevant in Studio.
