### ISSUE TITLE
Move the implementation of `buildFromConceptList` to `CanvasDataBuilder`

### ISSUE THREAD

**Issue by sorsaffari** [vaticle/typedb-studio#183]
`CanvasDataBuilder` currently supports individual concepts or answers that contain ConceptMaps. To serve its purpose as a module that unifies all logic involved in producing canvas data from all types of Graql answers, the logic implemented within `buildFromConceptList` should also be moved to the `CanvasDataBuilder`

**Comment by alexjpwalker** [comment]
This is no longer relevant in Studio.
