### ISSUE TITLE
Schema Designer: differentiating the visualisation of inherited roles

### ISSUE THREAD

**Issue by sorsaffari** [vaticle/typedb-studio#196]
## Problem to Solve

At the moment, when visualising the schema, we draw out edges from relation types to all their direct and inherited roleplayer types. This, especially in a heavily typed schema, can quickly lead to the canvas getting convoluted and, in extream cases, impossible to read.

## Current Workaround

deal with it.

## Proposed Solution

Simply put, we need to minimise the number of edges displayed in the schema designer. To scope both the problem and solution in this issue, we'll focus on how we can draw as few **role edges** as possible while leaving no room for misinterpretation and ambiguity. The role edges that we can avoid drawing are those that connect concept types to a relation that subtypes another relation. These edges are inferred via the use of `as` keyword in the definition of the relation. What follows are the schema definitions followed by how they'd be visualised, for two cases of role inheritance:

```
define
  R sub relation,
    relates A,
    relates B;

  SR sub R,
    relates A,
    relates C as B;

  SR-P-B sub entity,
    plays C;

  SR-P-A sub entity,
    plays A;
```
![IMG_0639](https://user-images.githubusercontent.com/1224721/64527577-2d986900-d2fe-11e9-9a18-203adfd43683.JPG)

In the illustration above:
- the dashed edge from `SR` to `SR-P-A` is the convention used to illustrate the non-overridden inherited role `A`.
- the label on the edge from `SR` to `SR-P-B` is extended with `as B` to illustrate that the edge in question represents the role `C` that overrides role `B` of `R`

Note that the `as <role>` and dashed edge only appear when the user hovers over either one of the connected nodes.

**Comment by jamesreprise** [comment]
We don't have a schema designer anymore and this issue is old. 

If differentiating the visualisation of inherited roles is desired then we can look at this in the future.
