### ISSUE TITLE
Use canvasToDOM in e2e > helpers > canvas

### ISSUE THREAD

**Issue by sorsaffari** [vaticle/typedb-studio#201]
At the moment, in order to obtain the offset values based on a given node's coordinates within the canvas, we have our own implementation that takes into account the window's width and height. However, VisJS network library has the `canvasToDOM` method for this exact purpose. We should alter the code to make use of this method.

**Comment by alexjpwalker** [comment]
This issue is no longer relevant as we no longer use VisJS but rather have our own visualisation code in Studio.
