### ISSUE TITLE
Provide Grakn Console

### ISSUE THREAD

**Issue by tapple** [vaticle/typedb-studio#241]
## Problem to Solve
Running write queries is not currently possible in Workbase.

## Current Workaround
Using Grakn Console.

## Proposed Solution
Allow users to access the Grakn Console within Workbase.

## Additional Information
As an enhancement to the current alternative (Grakn Console), the console accessed via Workbase should allow for multiline queries.

**Comment by sorsaffari** [comment]
@tapple Thanks for this feature request. I have updated the issue description to conform to our Feature Request template.

**Comment by alexjpwalker** [comment]
We have moved from Workbase to Studio.

We are not planning to embed Console into Studio, however the requested feature (running Write queries) will be available, and is tracked by the following issue:
- #438
