### ISSUE TITLE
Create a Bazel target for deploying to RPM

### ISSUE THREAD

**Issue by lolski** [vaticle/typedb-studio#25]
Use `//:deploy-rpm` from https://github.com/graknlabs/bazel-distribution to deploy to RPM in repo.grakn.ai

**Comment by lolski** [comment]
Blocked. We can't use  due `bazel-distribution` rules due to https://github.com/graknlabs/workbase/issues/17

**Comment by mariusa** [comment]
#17 was closed. How can we get a workbase RPM in repo.grakn.ai, please? 
(with or without bazel)

**Comment by alexjpwalker** [comment]
@lolski is this still something we should do?

**Comment by vmax** [comment]
@alexjpwalker I believe we have decided to abandon RPM packaging everywhere (including TypeDB Core)

**Comment by alexjpwalker** [comment]
Awesome.

If the user is on a Red Hat distribution they are able to run TypeDB Studio using our Linux Java binary package:
- https://github.com/vaticle/typedb-studio/issues/461

I will therefore close this issue as it is not something we plan to support in the foreseeable future.
