### ISSUE TITLE
Workbase double clicking an attribute should fetch also it's attribute-attribute relations

### ISSUE THREAD

**Issue by maydanw** [vaticle/typedb-studio#253]
## Problem to Solve
Currently, double-clicking an attribute does not fetch its relations. Adding this behavior will improve the software's work consistency.

## Current Workaround
Currently, I can make a direct query to fetch the missing relations

## Proposed Solution
Double-clicking an attribute should fetch its relations like in entities nodes.

**Comment by alexjpwalker** [comment]
Thanks for the report! This will be fixed in TypeDB Studio. You can track the progress of the issue here:
- #502 
- #498

**Comment by alexjpwalker** [comment]
duplicates #502
