### ISSUE TITLE
Navigate between queries in the UI (where we enter the query)

### ISSUE THREAD

**Issue by neomatrix369** [vaticle/typedb-studio#255]
## Problem to Solve

Not easy to move between written or saved queries in the current UI.

## Current Workaround

Find where the left panel options are and use them from there. 

## Proposed Solution

Buttons representing previous and next sections are at the bottom of each section - easier to navigate when you are looking through for things.

## Additional Information

On the back of the [slack channel discussions](https://grakn-community.slack.com/archives/C3DS7RW2J/p1580049491044900)

**Comment by alexjpwalker** [comment]
Good news - query tabs are being introduced into TypeDB Studio!

You can track the progress of the query tab feature at:
- #423 
- #424 
- #484 
- #485
