### ISSUE TITLE
[Docs] [minor] Download and installation of Workbase - instructions, steps, highlights

### ISSUE THREAD

**Issue by neomatrix369** [vaticle/typedb-studio#258]
## Problem to Solve

Clearer steps for installing workbase for different OS users - although minor it's important and will raise less queries from new users.

## Current Workaround

Need a bit of past knowledge and might come across tricky for newbies or less technical business users

## Proposed Solution

In addition to the Download section - some highlight on how Workbase just works out of the box by downloading and running it can help. If there is setup involved in each OS then mentioning that is also good for completeness.

Like for the macOS this is out of the box, download, click on the DMG, drag the icon into Application. But that's, not it, you need to tell your Security setting that please allow Grank to run or else you get a message saying “Grakn Workbase” can’t be opened because it was not downloaded from the App Store.".  <== this is solvable but helps to tell the user.

Like this, each OS might have small nuances to inform the user.

Just to be aware your fantastic product will be used by domain experts and they may not be tech-savvy! Every little push helps move this forward! 

## Additional Information

On the back of the [slack channel discussions](https://grakn-community.slack.com/archives/C3DS7RW2J/p1580049491044900)

**Comment by alexjpwalker** [comment]
Thanks for the report. These are extremely helpful points to raise and we will address them as we update our Docs for the production release of TypeDB Studio.

I've migrated this issue to https://github.com/vaticle/docs/issues/572.
