### ISSUE TITLE
[Docs] Graql docs might need better naming of .gql files

### ISSUE THREAD

**Issue by neomatrix369** [vaticle/typedb-studio#260]
## Problem to Solve

In the https://dev.grakn.ai/docs/general/quickstart doc, schema.gql is too generic, call it friendship-schema.gql, or something more descriptive - maybe grakn-friendship-schema.gpl! They will be downloading more such schemas in the future, from your site and elsewhere, let them not be lost in their download folder.

Question: Feel free to study the content of social-network-schema.gql. <=== which schema is this talking about, please fix this if its a typo?

## Current Workaround

Keep track of the .gql files downloaded.

## Proposed Solution

Give relevant graql download files representative names.

## Additional Information

On the back of the [slack channel discussions](https://grakn-community.slack.com/archives/C3DS7RW2J/p1580049491044900)

**Comment by alexjpwalker** [comment]
Migrated to https://github.com/vaticle/docs/issues/570
