### ISSUE TITLE
Error reported by Workbase but no logs (intermittent)

### ISSUE THREAD

**Issue by neomatrix369** [vaticle/typedb-studio#261]
## Description

Error reported by Workbase but no logs (intermittent) via a browser popup.

## Environment

Grakn version: 1.6.2
OS of Grakn server: Linux 812faf5f3972 4.19.76-linuxkit (Docker container)
Workbase version: 1.2.7
OS of Workbase: Mac OS 10.13.6
Other environment details:

## Reproducible Steps

**I admit it's no reproducible** :(

I loaded Workbase, paste my query:
```
match $p isa person, has full-name $fn; get; sort $fn; offset 100; limit 10;
```

And got a popup notification with this message:
```
Cannot read property 'tab-1' of undefined
```

## Expected Output

Some log with the error message in it, and maybe stacktrace to report to the amazing GraknLabs team!

## Actual Output

A popup with this message:

```
Cannot read property 'tab-1' of undefined
```
 
## Additional information

On the back of the [slack channel discussions](https://grakn-community.slack.com/archives/C3DS7RW2J/p1580049491044900)

**Comment by alexjpwalker** [comment]
We've moved from Workbase to Studio. This error will not occur in Studio.
