### ISSUE TITLE
[Docs] yarn install: There appears to be trouble with your network connection. Retrying... (dev mode)

### ISSUE THREAD

**Issue by neomatrix369** [vaticle/typedb-studio#263]
## Problem to Solve

When running:
```
$ yarn install
```
We can get errors like this appears in the console:

```
There appears to be trouble with your network connection. Retrying...
``` 

This is unrelated to Workbase but installation and running of the app for developers can become bit frustrating if they can't solve such problems and sometimes it seems unreasonable from the point of view of `yarn` users.

Even though this appears to be a [known issue](https://github.com/yarnpkg/yarn/issues/4890) the solutions suggested on the git issue may not work.

## Current Workaround

For me what seems to have worked is following the suggestions by the last post on this [SO link](https://stackoverflow.com/questions/43061045/yarn-install-cause-trouble-with-network-connection).

And then running worked for me:
```
$ yarn install --no-lockfile --network-timeout=1000000
```

Although you might have better solutions - please suggest.

## Proposed Solution

Suggest a solution or use the links above and mention this somewhere in your docs - either under troubleshooting or known issues or both. Let the users read this first before they go ahead.

**Comment by chungweileong94** [comment]
In my case, `yarn install --network-timeout=1000000` worked for me

**Comment by alexjpwalker** [comment]
Thanks for the report. We've moved from Workbase to Studio, which is built in the Compose framework, written in Kotlin using the JVM, and therefore `yarn` issues will no longer be relevant. Indeed, moving away from the `npm` ecosystem was one of our key reasons for moving to Compose.
