### ISSUE TITLE
Rethink the implementation of `buildRPInstances` in `CanvasDataBuilder.js`

### ISSUE THREAD

**Issue by sorsaffari** [vaticle/typedb-studio#285]
think about how this function can be rewritten to still be 100% non-blocking but at the same time be less nested and more readable.

https://github.com/graknlabs/workbase/blob/c67e442a8d73bb2f15e11d1ca43243da8c743584/src/renderer/components/shared/CanvasDataBuilder.js#L558-L596

**Comment by alexjpwalker** [comment]
This issue is no longer relevant as we have rewritten the codebase.
