### ISSUE TITLE
Use the CanvasDataBuilder for constructing nodes and edges off of a ConceptList

### ISSUE THREAD

**Issue by sorsaffari** [vaticle/typedb-studio#310]
The `CanvasDataBuilder` introduced since 1.2.3, currently only handles ConceptMaps. This has resulted in having two different approaches in constructing nodes and edges. The goal of this refactor is to leverage the CanvasDataBuilder to also handle ConceptLists in order to introduce a unified approach in constructing nodes and edges.

**Comment by alexjpwalker** [comment]
We don't have ConceptList or CanvasDataBuilder anymore.
