### ISSUE TITLE
When switching back to a tab with many nodes, there is a delay before the nodes show up

### ISSUE THREAD

**Issue by sorsaffari** [vaticle/typedb-studio#319]

**Comment by alexjpwalker** [comment]
This should be retested in Studio once we have:
- #507 

_Note that some delay is inevitable - it is not workable to always render every tab. But it should be an acceptable delay._

**Comment by jamesreprise** [comment]
This doesn't seem to be an issue with Studio (this issue was originally filed for Workbase). I suppose it depends how many is meant by 'many' nodes.
