### ISSUE TITLE
References stored in `schema-node-positions` (electron storage) are not unique across multiple keyspaces

### ISSUE THREAD

**Issue by sorsaffari** [vaticle/typedb-studio#333]
## Description
Position of schema nodes are referenced by the nodes' IDs (i.e schema concept IDs) and given that Grakn does not guarantee unique concept IDs across multiple keyspaces, the logic for restoring schema nodes' positions can break.

## Environment

1. Grakn version: Grakn Core 1.8.0
2. Workbase version: 1.3.4

## Reproducible Steps
Reproducing this issue involves creating and visualising mocked node objects.

1. Make it so that the schema for keyspace A and keyspace B both contain a node with id `123`.
2. Open the Schema Designer
3. Select keyspace A and move node `123` to a different position.
3. Select keyspace B

## Expected Output

Node `123` (when keyspace B is selected) to be positioned in the centre of the canvas.

## Actual Output

Node `123` (when keyspace B is selected) is positioned at the same coordinates at node `123` of keyspace A.
 
## Additional information
One solution may be prefixing references to nodes within `schema-node-positions` with the keyspace name.

**Comment by alexjpwalker** [comment]
This issue is no longer relevant in Studio
