### ISSUE TITLE
Keyspaces menu does not accommodate long keyspace names properly

### ISSUE THREAD

**Issue by sorsaffari** [vaticle/typedb-studio#344]
![unknown](https://user-images.githubusercontent.com/1224721/91971730-94820f80-ed11-11ea-9b00-15242a215baf.png)

**Comment by alexjpwalker** [comment]
We should retest this in Studio.

**Comment by jamesreprise** [comment]
<img width="359" alt="image" src="https://user-images.githubusercontent.com/51956016/175004374-55d803cf-3949-4929-af1e-6f166e981fe7.png">

Studio automatically adjusts the width of the database selector to adjust for this.

Let us know if you think this isn't the case or could be improved for longer database names.
