### ISSUE TITLE
Abort Querry

### ISSUE THREAD

**Issue by gitvge** [vaticle/typedb-studio#345]
Please replace every line in curly brackets ( { like this } ) with appropriate answers, and remove this line.

## Problem to Solve

When having a long running query running, WB has no option to abort it.

## Current Workaround

ctrl/command + r 

## Proposed Solution

button, key command to abort a running query

## Additional Information

-

**Comment by alexjpwalker** [comment]
Thanks for the report. This issue duplicates https://github.com/vaticle/typedb-studio/issues/156 .
