### ISSUE TITLE
White background color display option (printerfriendly)

### ISSUE THREAD

**Issue by gitvge** [vaticle/typedb-studio#349]
Please replace every line in curly brackets ( { like this } ) with appropriate answers, and remove this line.

## Problem to Solve

WB background color only black is not useful when using it for documentation (printerfriendly).

## Current Workaround

none

## Proposed Solution

-

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by alexjpwalker** [comment]
Thanks for the report. This issue is now tracked in:
- #436
