### ISSUE TITLE
Click graph exploration via "plays" (not only "relates")

### ISSUE THREAD

**Issue by gitvge** [vaticle/typedb-studio#351]
Please replace every line in curly brackets ( { like this } ) with appropriate answers, and remove this line.

## Problem to Solve

When exploring the graph with the mouse it works only in the "relates" direction, not in the "plays" direction of relations.

## Current Workaround

none

## Proposed Solution

Allow to explore the graph also in the "plays"-direction, e.g. ctrl-click.

## Additional Information

-

**Comment by alexjpwalker** [comment]
Thanks for the report. This issue is now tracked as part of:
- #498 
- #499
