### ISSUE TITLE
Stay in keyspace when switching between schema and data

### ISSUE THREAD

**Issue by gitvge** [vaticle/typedb-studio#352]
Please replace every line in curly brackets ( { like this } ) with appropriate answers, and remove this line.

## Problem to Solve

When loading a keyspace and switching to the schema view, the keyspace is not taken-over and the user has to select it.

## Current Workaround

select keyspace

## Proposed Solution

Keep the keyspace when switching to schema and back.

## Additional Information

none

**Comment by alexjpwalker** [comment]
Thanks for the report. We've moved from Workbase to Studio which no longer has a schema designer view, so this issue is no longer relevant.
