### ISSUE TITLE
Grakn KGMS form popup after IP connection on workbase? 

### ISSUE THREAD

**Issue by yuis-ice** [vaticle/typedb-studio#354]
## Description

Grakn KGMS form popup after IP connection so cannot use workbase. I thought Grakn is free to use without business registration, isn't it? I'm new to here so maybe this is just my misunderstanding but anyway I need your comment about this. 

## Environment

1. Grakn version: grakn-core-server-windows-1.8.3
2. OS of Grakn server: windows 10
3. Workbase version: 1.3.6
4. OS of Workbase: windows 10
5. Other environment details: 

## Reproducible Steps

Steps to create the smallest reproducible scenario:

// cmd admin 
```
CD C:\_grakn-core-server-windows-1.8.3
grakn.bat server start // checked ip:port 
```

// workbase 
open workbase exe
enter the ip port info and click connect 
the username/password form and login button appeared

![https://yuis.xsrv.jp/images/ss/ShareX_ScreenShot_a3e20417-92e9-4b45-9f09-46ba2f123e59.png](https://yuis.xsrv.jp/images/ss/ShareX_ScreenShot_a3e20417-92e9-4b45-9f09-46ba2f123e59.png)

## Expected Output

{ Please describe what you expected to happen. }

## Actual Output

{ Please describe what actually happened. }
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by DiligentDilettante** [comment]
I can confirm this happens on both the latest Linux and Windows releases, and makes it not possible to use workbase with a Grakn core server. I'm currently building from source and I'll also run a dev server to see if this behavior remains in those usage patterns.

**Comment by alexjpwalker** [comment]
Thank you for the report. Workbase has been replaced with a new graph visualisation software and IDE tool, TypeDB Studio. You can download the latest release of TypeDB Studio at https://vaticle.com/download#typedb-studio.
