### ISSUE TITLE
Windows prevented installation due to missing certificate

### ISSUE THREAD

**Issue by TNO-Knowledge-Based-Systems** [vaticle/typedb-studio#360]
## Description

While installing the last version of the Workbase (1.3.6) I encountered a security install problem. 
This could be due to security settings on the laptop. But it could be that Windows did some security updates which prevent the Workbase from installing easily. 

## Environment

Workbase version: 1.3.6
OS of Workbase: Windows 10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Download Windows Grakn Workbase installer for 1.3.6.
2. Run installer as administrator.

## Expected Output

Grakn Workbase is installed.

## Actual Output

Windows Protected your PC.
Microsoft Defender prevented unrecognized app from starting.
 
## Additional information

Not sure if this is due to security settings (which I am not allowed to change) or due to new Windows installations and therefore a problem for others in the community.

**Comment by TNO-Knowledge-Based-Systems** [comment]
Turns out you probably have to make a whole certificate (which could be costly) to fix this and this probably is a security issue.
Therefore not sure if it is worth for you to dive into it.

**Comment by alexjpwalker** [comment]
Thank you for reporting this issue! We've reached the same conclusion - we need to obtain a certificate and a physical signing key which are costly for Windows.

We will look into this at a later date.

**Comment by alexjpwalker** [comment]
Once we've built (and, presumably, deployed) the Windows EXE for the new Studio, we should consider [submitting it to Microsoft for malware analysis](https://www.microsoft.com/en-us/wdsi/filesubmission?persona=SoftwareDeveloper).

This prevents the need for buying an EV code signing certificate, which incurs a recurring yearly cost (as well as the need to develop the build system code to actually sign Studio with it). But, if we go with the "submitting it to Microsoft" option, that does need to be performed every time we release an update to Studio thereafter.

source: https://stackoverflow.com/a/66582477/2902555

**Comment by alexjpwalker** [comment]
We submitted TypeDB Studio 2.11.0 to Microsoft Security Intelligence, and got the response within a day that it has been cleared and should no longer be flagged by SmartScreen. Hooray!

We'll need to do this each time we create a new release of Studio. Closing this issue now, but we will continue to use it as reference.
