### ISSUE TITLE
Error when defining any rule in Workbase 

### ISSUE THREAD

**Issue by tomassabat** [vaticle/typedb-studio#370]
## Description

I get an error when trying to define a rule in Workbase. 

## Environment

Grakn version: grakn-core-2.0.0-alpha-9
OS of Grakn server: Mac OS 10
Workbase version: Grakn Workbase 2.0.0-alpha
OS of Workbase: Mac OS 10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run Grakn and start Workbase's schema editor
2. Try to define this new rule in the schema editor: 
```
rule mew-new:
when {
	$x isa thing;
	}
then {
	(spouse: $x) isa marriage;
};
```
3. See error at the bottom

## Actual Output

Error: 
![image](https://user-images.githubusercontent.com/20223184/111076930-577bae80-84e6-11eb-8594-3bd7c90e149b.png)

**Comment by lriuui0x0** [comment]
I think we can try:

when:
```
{$x isa person;}
```

then:
```
$x has age 70;
```

**Comment by tomassabat** [comment]
Doesn't seem to work either @lriuui0x0, see below:
![image](https://user-images.githubusercontent.com/20223184/111134892-f6022100-8573-11eb-8963-45894adc5479.png)

**Comment by lriuui0x0** [comment]
@tomassabat OK sorry what you need to do is:

```
(spouse: $x) isa marriage
```

instead of 

```
(spouse: $x) isa marriage;
```

(note the semicolon)

**Comment by tomassabat** [comment]
Yes, this works @lriuui0x0

**Comment by alexjpwalker** [comment]
Something dodgy is going on at the client level because the following Graql syntax works:
```gql
define
      rule tortoises-become-old-at-age-1-year: when {
        $x isa tortoise, has age $a;
        $a > 0;
      } then {
        $x has is-old true;
      };
```
Chances are we need to fix this in client-java and Grakn Core.

**Comment by tomassabat** [comment]
@lriuui0x0 removing the semi-colon now does not work now, it's throwing up the same error, why is that? This is with the latest Workbase
![image](https://user-images.githubusercontent.com/20223184/111208880-3b017400-85c3-11eb-85d7-01a7a8e8bd41.png)

**Comment by alexjpwalker** [comment]
I'm closing this issue because we have moved from Workbase to Studio and the Workbase schema designer will no longer be maintained.
