### ISSUE TITLE
Undefine relation in Grakn workbase 

### ISSUE THREAD

**Issue by daniel-crowe** [vaticle/typedb-studio#381]
## Description

When attempting to "delete" a relation within Grakn Workbase schema editor, an error is returned and the relation is not undefined.

## Environment

Grakn version: grakn-core-2.0.0-alpha-9
OS of Grakn server: Mac OS 10
Workbase version: Grakn Workbase 2.0.0-alpha-2.4733
OS of Workbase: Mac OS 10

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Run Grakn and start Workbase
2. Define an attribute or two
3. Open schema editor and select database
4. Right click one attribute and select "delete"
5. See error

## Expected Output

- "undefine schema element successful" message
- relation is removed

## Actual Output

![image](https://user-images.githubusercontent.com/57318771/111306443-17d0d600-8650-11eb-9a94-3921f750330c.png)

**Comment by lriuui0x0** [comment]
@daniel-crowe As mentioned in discord. This seems to be a legit error. It complains that some entities that plays the relation role have instances, which is disallowed by server. Can you check if that's the case?

**Comment by alexjpwalker** [comment]
As we have moved from Workbase to Studio, this issue is no longer applicable.
