### ISSUE TITLE
provide docker image

### ISSUE THREAD

**Issue by flashpixx** [vaticle/typedb-studio#391]
## Problem to Solve

Is it possible to provide a docker image for workbase similar to the server

## Proposed Solution

Creating a docker image on https://hub.docker.com/u/graknlabs for the workbase if possible, so it can used as a web application within the browser

**Comment by alexjpwalker** [comment]
We've rewritten Workbase into a new product, TypeDB Studio, which is not a web application - it is not even an Electron application, so it doesn't use Web technology at all.
