### ISSUE TITLE
Encourage key use for entities

### ISSUE THREAD

**Issue by alexjpwalker** [vaticle/typedb-studio#395]
## Problem to Solve

We want to move away from using IIDs to identify Things, preferring to encourage the use of keys. But currently, a key ownership is not even distinguishable from an attribute ownership in Workbase.

## Proposed Solution

Attribute ownerships should be highlighted if they are key ownerships.

We could do this either in the Visualiser (using a special colour, perhaps?) or in Type Details, we could mark the key ownership(s) with an asterisk, or bold text, or a 🔑 emoji, or some other kind of highlight. Or list them above the others, in a separate table perhaps.

Given that modifying Type Details is a much more easily tolerable change, we should do it there.

**Comment by jamesreprise** [comment]
<img width="871" alt="image" src="https://user-images.githubusercontent.com/51956016/175010628-644c2ee3-a722-4168-a7c9-c1bf712ca55c.png">
We have a key field on the type page with a tick. Do we want to add some indication of this being a key to the type browser?
<img width="269" alt="image" src="https://user-images.githubusercontent.com/51956016/175011049-807f715f-911b-489d-b60a-658398a06bb1.png">

**Comment by jamesreprise** [comment]
Looking at the problem to solve section: we do now distinguish keys from normal attributes on the type page (or "Type Details" as we referred to it), as seen above.
