### ISSUE TITLE
Limit query result size to 1000 unless an explicit limit is specified

### ISSUE THREAD

**Issue by alexjpwalker** [vaticle/typedb-studio#435]
It's too easy to type `match $x isa thing`, run it, and end up fetching millions of answers, which may be far more than the user has any use for, and may cause performance difficulties in Studio, particularly in graph output.

It would be nice for Studio to set a default limit and stop fetching answers beyond that (but this should be overridable). We should behave similarly to SQL Management Studio, setting a default limit of 1000 unless the user explicitly specifies the limit in their query.

**Comment by jamesreprise** [comment]
When users hit this limit, they should be notified of that.

**Comment by jamesreprise** [comment]
Closed by https://github.com/vaticle/typedb-studio/pull/623.
