### ISSUE TITLE
Error dialog typeface is not fixed-width, so syntax errors point to write part of the query

### ISSUE THREAD

**Issue by danielsmith-eu** [vaticle/typedb-studio#476]
Using TypeDB Studio 2.4.0 (from homebrew on MacOS 11.6 Big Sur)

The explanation of the query error shows the location of the error incorrectly:

<img width="692" alt="Screenshot 2021-10-19 at 13 39 34" src="https://user-images.githubusercontent.com/613776/137911482-d28ce5e9-f198-4273-975f-5ee32790090e.png">

In the server console it shows the correct location of the error (i.e. with the carat symbol pointing the above line):

<img width="805" alt="Screenshot 2021-10-19 at 13 43 09" src="https://user-images.githubusercontent.com/613776/137911651-f275a71f-abe0-4aca-90ae-6cff2472432a.png">

To resolve this, the bit of the error dialog that shows lines from the server should use a fixed-width typeface.

**Comment by lolski** [comment]
thank you for reporting the bug @danielsmith-eu !

**Comment by alexjpwalker** [comment]
This issue will be resolved in the new version of Studio with an overhauled architecture. Errors will be displayed in **Log Output**, which uses a monospace font.
