### ISSUE TITLE
Preference to turn file autosave on/off

### ISSUE THREAD

**Issue by alexjpwalker** [vaticle/typedb-studio#484]
## Problem to Solve

Right now, every edit onto a text file is saved automatically. We should provide the ability to turn this off for the user to trigger saving manually.

## Current Workaround

None.

## Proposed Solution

The functionality is already implemented under-the-hood. We just need to implement a way to configure the auto vs manual save mode.

## Additional Information

None.

**Comment by FrankUrbach** [comment]
Hi Alex
I would like to extend this topic. It would be cool if it would be possible to determine a directory where some default queries could be stored and named as wanted.

**Comment by alexjpwalker** [comment]
> Hi Alex I would like to extend this topic. It would be cool if it would be possible to determine a directory where some default queries could be stored and named as wanted.

Yes. We are moving towards this being the standard behaviour, by requiring the user to create a "workspace directory" at startup, much like all major IDEs do.

**Comment by jamesreprise** [comment]
Closed by https://github.com/vaticle/typedb-studio/pull/623.
