### ISSUE TITLE
Allow entering multiple Cluster server addresses

### ISSUE THREAD

**Issue by alexjpwalker** [vaticle/typedb-studio#488]
## Problem to Solve

Users are encouraged to enter all the Cluster server addresses when connecting via a Client, but are currently unable to do so via Studio.

## Proposed Solution

- [ ] The TypeDB Cluster tab in the Connection form should contain a multiline text field for the server addresses, and state that the server addresses should be passed in as a multiline string
- [ ] To maximise ease of use, we should accept comma-separated and semicolon-separated lists as well

**Comment by jamesreprise** [comment]
- https://github.com/vaticle/typedb-studio/pull/646
