### ISSUE TITLE
Blank window on launch

### ISSUE THREAD

**Issue by Mohsyn** [vaticle/typedb-studio#525]
Typedb Studio for Windows 2.4.0 alpha
installs without error
blank window on launch
there are no errors

**Comment by alexjpwalker** [comment]
Thanks for the report. Are you using 2.4.0-alpha-3? There is a known issue in 2.4.0-alpha-3 that can cause this. If so, please upgrade to 2.4.0-alpha-4.

We have a release in progress that should display a more useful message when a fatal error occurs; this should prevent issues like this in the future.

**Comment by Mohsyn** [comment]
i tried 2.4.0-alpha-4

**Comment by alexjpwalker** [comment]
Thanks. There's one thing you can try to diagnose the problem:

- Open Event Viewer
- Check the "Windows Logs > Application", "Windows Logs > System" and "Applications and Services Logs". It's likely that Studio emitted an Error to one of these logs.

Let me know if you're able to find anything.

**Comment by Mohsyn** [comment]
The program typedb-studio-windows.exe version 2.4.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 4c5c
 Start Time: 01d80d0bee56273d
 Termination Time: 4294967295
 Application Path: C:\Program Files\typedb-studio-windows\typedb-studio-windows.exe
 Report Id: 5de5a971-eb6e-4921-b6b0-12be6d187fd0
 Faulting package full name: 
 Faulting package-relative application ID: 
 Hang type: Top level window is idleThe program typedb-studio-windows.exe version 2.4.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 4c5c
 Start Time: 01d80d0bee56273d
 Termination Time: 4294967295
 Application Path: C:\Program Files\typedb-studio-windows\typedb-studio-windows.exe
 Report Id: 5de5a971-eb6e-4921-b6b0-12be6d187fd0
 Faulting package full name: 
 Faulting package-relative application ID: 
 Hang type: Top level window is idle

**Comment by Mohsyn** [comment]
The program typedb-studio-windows.exe version 2.4.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 4c5c
 Start Time: 01d80d0bee56273d
 Termination Time: 4294967295
 Application Path: C:\Program Files\typedb-studio-windows\typedb-studio-windows.exe
 Report Id: 5de5a971-eb6e-4921-b6b0-12be6d187fd0
 Faulting package full name: 
 Faulting package-relative application ID: 
 Hang type: Top level window is idle

**Comment by alexjpwalker** [comment]
Unfortunately I don't think those logs shed any light on the problem.

My advice would be to test on a different machine if you have one available; otherwise wait for the next release - we've upgraded a number of our external library imports, which may fix the issue.

**Comment by alexjpwalker** [comment]
We've just released 2.10.0-alpha. Can you check if this issue is still reproducible?

**Comment by Mohsyn** [comment]
Yes it is resolved
Thanks
