### ISSUE TITLE
Double clicking/tapping on folder name quickly is unreliable

### ISSUE THREAD

**Issue by lolski** [vaticle/typedb-studio#526]
Users should be able to perform actions such as clicking on a button by tapping on the touchpad.

However, taps are often missed by Studio / Compose framework for some reason, resulting in users having to tap multiple times in order to perform an action.

We should make taps be detected reliably so that a user only needs to tap once to perform an action.

In contrast to taps, touchpad clicks work reliably.

**Comment by jamesreprise** [comment]
Using studio only by tapping on a touchpad has been reliable for me. @lolski was there a particular laptop you found this on? Could differ by model/device/year.

**Comment by jamesreprise** [comment]
From discussion in person: Double tapping on folder name in project navigation is unreliable when used rapidly. Needs a certain delay to register as separate double taps.

Interacting to expand with the expand arrow by folder is a single tap, but a double tap on the folder name.

**Comment by jamesreprise** [comment]
This is an issue with compose, Studio only receives messages from compose about whether something is a double primary input.

https://github.com/JetBrains/compose-jb/issues/358
https://github.com/JetBrains/compose-jb/issues/683

This is a pretty minor bug so it probably isn't worth working around, especially if it gets fixed upstream at some point.
