### ISSUE TITLE
Query pane stops rendering

### ISSUE THREAD

**Issue by mathieuisabel** [vaticle/typedb-studio#532]
I'm hitting an issue with alpha-5 where the query stops rendering. The only I could find to fix that would be to restart typedb-studio. See the following screenshot:

![image](https://user-images.githubusercontent.com/15805484/165324230-60cc53d5-9be3-438d-a0c4-451465ba57fe.png)

This happened to me when creating a new query tab or after running a query.

**Comment by alexjpwalker** [comment]
@mathieuisabel Thank you for reporting this issue!

In my experience, this issue occurs most commonly when:
1. Loading a query file;
2. Disconnecting from the server (with the "sign out" button) and connecting again

It's an issue with the code editor in the current Alpha release that we haven't been able to find an easy fix for. There will be a major Studio release very soon in which the code editor has been rebuilt from scratch, and does not have this issue.

**Comment by alexjpwalker** [comment]
This issue is fixed in 2.10.0-alpha.
