### ISSUE TITLE
Starting TypeDB Studio

### ISSUE THREAD

**Issue by LeoVincenzi** [vaticle/typedb-studio#533]
Hi everybody!
I am facing some issues in starting TypeDB Studio since, after the download of the source file, I cannot understand how to start the interface from the Linux terminal. 
I am using the TypeDB Server and I am able to create and populate a database. I would like now to visualize it and I have seen how to connect the interface with the database, what I am missing is how to open the visualizer interface.

Maybe it's a really simple passage, but it's not clear to me.

**Comment by alexjpwalker** [comment]
Hi @LeoVincenzi ,

Which distribution of TypeDB Studio have you installed? Is it the `linux-java-binary` (labelled as "Linux (cross-platform)" on vaticle.com)?

If so, you simply need to unzip the `tar.gz` file, `cd` into the unzipped folder, and run `./typedb-studio` in your terminal. You'll need Java installed on your machine, preferably Java 17.

Let me know if it works.

**Comment by jamesreprise** [comment]
@LeoVincenzi Hey there!

Are you still having this issue? Let us know if what Alex said in his comment helps at all.

**Comment by KrishnaPG** [comment]
Facing similar issue. Downloaded the Ubuntu DEB file for TypeDB-Studio. Installed it with `deb -i` command. Now it is not clear how to start or access the studio. (This is an ubuntu machine on cloud).

**Comment by alexjpwalker** [comment]
@KrishnaPG maybe try `dpkg -L typedb-studio` to find the install directory?

(source: https://askubuntu.com/questions/843294/where-does-a-deb-file-go-after-installation)

**Comment by alexjpwalker** [comment]
@KrishnaPG Are you still experiencing the issue?

**Comment by KrishnaPG** [comment]
@alexjpwalker Installed it on Windows. Was not able to make it run on Ubuntu.

**Comment by alexjpwalker** [comment]
To anyone struggling to find the TypeDB Studio installation directory on Ubuntu, I would recommend the use of `dpkg -L`.

We've raised the following issue for having the installer add the Studio binary path to the user or system `PATH` (or for some other strategy such as symlinking to enable running `typedb-studio` from the command line without knowing its real path):
- https://github.com/vaticle/typedb-studio/issues/630

Closing this issue now.
