### ISSUE TITLE
Set log or graph visualisation as default per-query (set to not render the graph)

### ISSUE THREAD

**Issue by thomaschristopherking** [vaticle/typedb-studio#550]
## Problem to Solve

The actual values of results (e.g., attribute values) are sometimes more important than the graph structure, and the graph structure can use up significant CPU on machines without a good GPU. Therefore, it is often desirable to see the log output only and not the graph visualisation.

## Current Workaround

Currently, I use a group query to force only a log output.

## Proposed Solution

A button to turn off graph visualisation and/or to default to the log output tab when the query is executed.

**Comment by jamesreprise** [comment]
We'll add this to the preferences page.

**Comment by jamesreprise** [comment]
Closed by https://github.com/vaticle/typedb-studio/pull/623.
