### ISSUE TITLE
Graph edges randomly missing

### ISSUE THREAD

**Issue by mathieuisabel** [vaticle/typedb-studio#551]
## Description

Running the same query, sometime the graph shows correctly the attribute ownership, sometime not.

## Environment

1. TypeDB version: 2.10
2. OS of TypeDB server: Windows 11
3. Studio version: 2.10-alpha-3
4. OS of Studio: Windows 11
5. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

Run the following query multiple times:

match $api isa api-service, has name $api-name;
$api-name = "GEMTriageAPI";

## Expected Output

Attribute ownership is correctly shown in the graph.

## Actual Output

Running the same query multiple times yields the following graph output:

![image](https://user-images.githubusercontent.com/15805484/171437730-a9c9cee9-1ae0-40b7-b72d-18cd567d2659.png)

![image](https://user-images.githubusercontent.com/15805484/171437786-b981a912-9d7a-4d3f-8f9b-19801b3c690e.png)

## Additional information

Log output seems constant:

## Running> Match query:
match
$api isa api-service,
    has name $api-name;
$api-name "GEMTriageAPI";

## Result> Match query successfully matched concepts in the database:
{
    $api-name "GEMTriageAPI" isa name;
    $api iid 0x826e80b08000000000000001 isa api-service;
}

**Comment by mathieuisabel** [comment]
This is especially painful when trying to troubleshoot inferred attributes. i.e. is it my rule or it`s the bug? :-D

**Comment by mathieuisabel** [comment]
Here's an example with subs:

![image](https://user-images.githubusercontent.com/15805484/171905099-4a5878e4-7f02-4103-8034-91f8f0cb4383.png)

**Comment by alexjpwalker** [comment]
I've updated the linked issue accordingly.

**Comment by alexjpwalker** [comment]
Fixed by https://github.com/vaticle/typedb-studio/commit/9ccc1349074305b9151eda7a115da2689e86e2ba which will go into the next release
