### ISSUE TITLE
Shift+End selects to end of file, not end of line

### ISSUE THREAD

**Issue by mathieuisabel** [vaticle/typedb-studio#555]
## Description

When doing Shift+End in a tab with multiple lines of queries/text, it will select up until the end of the file instead of up until the end of the line.

Same is true when doing the opposite with Shift+Home.

This doesn't match the standard behavior seen in most/all text editors.

I'm wondering if that's a WIndows only thing.

## Environment

1. TypeDB version: 2.10
2. OS of TypeDB server: Windows 11
3. Studio version: 2.10-alpha-4
4. OS of Studio: Windows 11
5. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

- Enter two lines of text in the editor
- Place your cursor at the beginning of the first line
- Hit Shift-End

## Expected Output

Select text up until the end of the current line.

## Actual Output

All text is selected.

**Comment by mathieuisabel** [comment]
Just to be clear, this not only Shift+End but Shift+Home as well.

**Comment by mathieuisabel** [comment]
Any chance this would get in the next release?

**Comment by alexjpwalker** [comment]
I agree, this seems like something we should fix in the near future.
