### ISSUE TITLE
Improve shape visualization

### ISSUE THREAD

**Issue by mathieuisabel** [vaticle/typedb-studio#556]
## Problem to Solve

Interpreting the graph is difficult as a lot of information is truncated in the shapes. i.e. Type names are cut if they don't fit in the preset shape size. Attributes are almost useless unless the attribute name is really short and the value as well, which rarely happens.

## Current Workaround

None

## Proposed Solution

Allow customization of the graph rendering behavior. At a minimum, maybe sale the shapes to include the full type name for entity/relation. For attributes, scale the shape so we can actually see more of the label+value.

Maybe also allow the option of just showing the value for the attribute instead of label+value.

Allowing for custom icons per entity or at least custom color coding per entity type would be really useful to quickly identify what is what.

**Comment by alexjpwalker** [comment]
This is a severe limitation of the current visualiser - we're still ironing out the details of the fix (which may well just be "scale the vertices as required") and should have this done, hopefully, within the next couple of Alpha releases.

This issue is tracked at
- https://github.com/vaticle/typedb-studio/issues/467

Closing as duplicate.

**Comment by mathieuisabel** [comment]
@alexjpwalker Perhaps that issue should be broken down into multiple ones as there are different independent things in Proposed solution. i.e. Scaling, coloring, custom icons, vertices/edges labeling text to use

**Comment by alexjpwalker** [comment]
Ah, right, I just saw the other things requested in this issue. I believe these are fully covered in other issues, apart from the custom icon which I can add in now to #436 .

- #436 
- #437
