### ISSUE TITLE
Pasting in TypeDB Studio fails

### ISSUE THREAD

**Issue by tomassabat** [vaticle/typedb-studio#559]
Please replace every line in curly brackets ( { like this } ) with appropriate answers, and remove this line.

## Description

Pasting a chunk of text in Studio fails.

## Environment

1. TypeDB version: TypeDB 2.9.0
2. OS of TypeDB server: Mac OS 12.1
3. Studio version: Master commit 63f33e0
4. OS of Studio: Mac OS 12.1:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Open a new tab
2. Paste text that is at least 2 lines 
3. Error appears, see video attached 

https://user-images.githubusercontent.com/20223184/172488143-429fbd69-0201-4731-93b0-1eab008f975d.mov

**Comment by haikalpribadi** [comment]
Fixed by reverting the commit in https://github.com/vaticle/typedb-studio/commit/34ca25a8a524d0428e1f62598371a69f9f0d555e
