### ISSUE TITLE
allow to replace (not only search)

### ISSUE THREAD

**Issue by gitvge** [vaticle/typedb-studio#572]
Please replace every line in curly brackets ( { like this } ) with appropriate answers, and remove this line.

## Problem to Solve

replace is not possible in studio

## Current Workaround

use another editor

## Proposed Solution

expand search with a replace feature addon, or directly with ctrl h

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by alexjpwalker** [comment]
@gitvge , as a temporary workaround can you try using `Ctrl+R` to replace?

I'm investigating why the shortcut is `Ctrl+R` and not `Ctrl+H`, as is standard on Windows/Linux machines.

**Comment by alexjpwalker** [comment]
We're changing the shortcut to `Ctrl+H` on Windows/Linux (ref: https://github.com/vaticle/typedb-studio/commit/95e8880f8658d9fa1cd9ca94adaee6fc7294aa31)

**Comment by alexjpwalker** [comment]
This fix will go into the next release.
