### ISSUE TITLE
Text Editor: Editing a line with Chinese fonts (or emojis) causes "blips" and incorrect selection ranges

### ISSUE THREAD

**Issue by alexjpwalker** [vaticle/typedb-studio#593]
## Description

- When typing into a line in the Text Editor that contains Chinese characters, if the position being typed into is later in the line than where the Chinese characters are, the cursor seems to very briefly "flicker" as it jumps from the end of the line, to the middle, and then back to the end again.
- When selecting to the end of a line in the Text Editor that contains Chinese characters, the selection does not actually reach the end of the line, but is cut off midway (see screenshot)

<img width="252" alt="image" src="https://user-images.githubusercontent.com/14253102/177304947-a1692ff1-970a-4d62-9fcc-b8eebd476593.png">

## Environment

1. Studio version: 2.10.0-alpha-10
2. OS of Studio: Mac OS 11

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Create a new untitled file, with content:
```
insert

$x "约书亚" isa name;

```
2. Try adding more characters to the end of the line containing Chinese text
3. Try selecting the whole file

## Expected Output

The operations should succeed normally

## Actual Output

- Adding more characters causes the cursor to "flicker" and jump briefly.
- Selecting the whole file doesn't catch the entire line - it misses a bit off the end

**Comment by jamesreprise** [comment]
Additional non-ascii related issue:
```
insert

$x "😀😀😀" isa name;
```

Backspacing through the emojis turns them into rats, pig noses, eyes depending on surrounding text.

**Comment by jamesreprise** [comment]
`AnnotatedString` attempts to do faulty indexing logic that doesn't respect emojis (and likely other `Char`s) as single characters. For example, 😊 is two separate `Char`s: `[\uD83D, \uDE0A]`.

**Comment by jamesreprise** [comment]
A potential approach would be for us to filter any character that isn't between 0000-FFFF. This doesn't include all Chinese, Japanese & Korean (CJK) characters as there are some CJK Unicode 'Extensions' that fall outside of this range:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/51956016/203010496-fe4a3b56-3a4a-4f8b-be6d-c227d93fec2d.png">

**Comment by jamesreprise** [comment]
After discussion, we think that it's actually `String` that performs this behaviour. As such, it's more likely that it's on us to pass in the appropriate indices to any string operations.
