### ISSUE TITLE
Ability to view expanded text on multiple shapes

### ISSUE THREAD

**Issue by mathieuisabel** [vaticle/typedb-studio#597]
Please replace every line in curly brackets ( { like this } ) with appropriate answers, and remove this line.

## Problem to Solve

Right now you can view the full (not quite sometimes) text on only two shape at a maximum.

## Current Workaround

None.

## Proposed Solution

- Add button to toggle expansion of all shapes in the graph.
- Being able to mult-select shapes and then toggle expansion only on those

## Additional Information

You can sort of cheat from 1 share with expansion to 2 shapes by clicking one shape first and then hover on a second one but that's about it. When you do that though, the rest of the graph is darkened/out of focus.

![image](https://user-images.githubusercontent.com/15805484/179228343-9c745f7e-8468-42ad-9c71-f9f071d68192.png)

**Comment by alexjpwalker** [comment]
This is planned as part of:

- https://github.com/vaticle/typedb-studio/issues/436

The planned fix is:

> Vertex/edge customisations should be applicable at the following levels:
> - All vertices
> - All vertices of a given Concept Type
> - All vertices of a given Concept Encoding
> [...]
>
> We should be able to customise the following properties:
> - Vertex shape and size mode ('stretch to fit' vs. 'fixed', default is 'fixed')
> [...]

**Comment by jamesreprise** [comment]
This is planned in the referenced issue: https://github.com/vaticle/typedb-studio/issues/436
