### ISSUE TITLE
Studio freezes when undoing/redoing changes to large chunks of text

### ISSUE THREAD

**Issue by tomassabat** [vaticle/typedb-studio#599]
## Description

Studio freezes and has to be restarted when undoing/redoing changes that affect large chunks of text.

## Environment

1. TypeDB version: 2.11.1
2. OS of TypeDB server: MacOS 12.1
3. Studio version: 2.11.0
4. OS of Studio: MacOS 12.1

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Select any large chunk of text in Studio (e.g. 200+ lines)
2. Use the tab button many times to create indentations
3. Studio should freeze

**Comment by jamesreprise** [comment]
It appears as though the rate at which the indents and outdents are performed is the biggest factor.

Performing 10 indents and then 10 outdents one second apart is completely fine. The increase in memory usage is nominal (20MB or so). Doing it quickly freezes the program, allocating enormous amounts of memory (up to 6GB) in the process.

I suspect that there is some sort of backpressure issue here, where if actions aren't processed quickly enough the system locks up.

**Comment by jamesreprise** [comment]
This is no longer reproducible on the development branch after other work has been done upgrading compose and making changes to how the text editor functions under the hood. Closing.
