### ISSUE TITLE
Config to toggle between automatic and manual save

### ISSUE THREAD

**Issue by haikalpribadi** [vaticle/typedb-studio#614]
## Problem to Solve

Right now, every edit onto a text file is saved automatically. I think should provide the ability to turn this off for the user to trigger saving manually.

## Current Workaround

None.

## Proposed Solution

The functionality is already implemented under-the-hood. We just need to implement a way to configure the auto vs manual save mode.

## Additional Information

None.

**Comment by alexjpwalker** [comment]
Closing this issue as duplicate, but merging the issue description into the other issue:

- duplicates https://github.com/vaticle/typedb-studio/issues/484

**Comment by jamesreprise** [comment]
I've bundled this in with https://github.com/vaticle/typedb-studio/issues/607.
