### ISSUE TITLE
.tql file displays Chinese garbled characters

### ISSUE THREAD

**Issue by qqliang** [vaticle/typedb-studio#627]
Please replace every line in curly brackets ( { like this } ) with appropriate answers, and remove this line.

## Description

While using TypeDB Studio creates xxx.tql file and inputs some Chinese, it displays Chinese garbled characters.
![image](https://user-images.githubusercontent.com/23022359/191966553-88995095-00cb-4923-bea4-33bcce93b33b.png)

## Environment

1. TypeDB version: TypeDB 2.11.0
2. OS of TypeDB server: Ubuntu 16.4 
3. Studio version:  2.11.0
4. OS of Studio:  Windows 10 
5. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. click plus button to create .tql file
2. type some typeql code with Chinese comments
3. save file
4. Chinese comments display garbled characters

## Expected Output

Display Chinese normally!

## Actual Output

Chinese comments display garbled characters, as shown as following screenshot
![image](https://user-images.githubusercontent.com/23022359/191968185-ea148f8d-5461-4eb3-95cb-7b3f1e12e4a9.png)

**Comment by jamesreprise** [comment]
Many thanks for your report @qqliang, there are problems with support for Chinese language characters within our Text Editor currently and this is within the current milestone to be fixed, see: 
- https://github.com/vaticle/typedb-studio/issues/593

When you say the characters are garbled, are they completely incorrect as they are typed in or only when edited later on? Also, just to check, we italicise all text. Are you referring to this italicisation effect at all when you say garbled?
<img width="454" alt="image" src="https://user-images.githubusercontent.com/51956016/192513458-85d8eeee-64da-483e-8c5d-0fd68c074410.png">

**Comment by qqliang** [comment]
Thanks for your reply. While typing Chinese characters to Text Editor, it shows correctly. But when I press Ctrl+S to save and reopen, it shows garbled. Example is as follows: [image] [image]

**Comment by jamesreprise** [comment]
We have a solution in the works for this issue now. I'm closing this as a duplicate and merging with:
- https://github.com/vaticle/typedb-studio/issues/593
as we have more information there.
