### ISSUE TITLE
Configure transaction timeout

### ISSUE THREAD

**Issue by suciokhan** [vaticle/typedb-studio#642]
## Problem to Solve

Transactions timeout before query can complete in TypeDB Studio, and there is no way for a user to modify the timeout limit.

## Current Workaround

Execute query using Python Client and custom transaction timeout, and then transform data into node and edge tables for visualization in a separate system (Cytoscape, Gephi, etc.). This is slow and cumbersome, in part due to the complexity of parsing results from the Python Client (a separate issue).

## Proposed Solution

Add-in a menu option for the user to modify the transaction timeout for queries in the GUI. In my organization, I want people with no programming experience to be able to query my database. If the queries timeout, they are unable to use it, which significantly reduces the usability of TypeDB in my organization (if only the data scientists can use it, it's of no use to the analysts, who stand to benefit the most from the database I built).

## Additional Information

NA

**Comment by alexjpwalker** [comment]
Thanks for the report! Yeah, the transaction timeout being fixed to 5 minutes is a problem.
