### ISSUE TITLE
Save and load the state of the graph visualiser in Workbase

### ISSUE THREAD

**Issue by BFergerson** [vaticle/typedb-studio#66]
![screenshot from 2018-11-01 13-54-03](https://user-images.githubusercontent.com/3278877/47881149-8b0c8100-dde2-11e8-9859-3f9ff575e0f8.jpg)

The above graph shows the AST structure of a Java program (left) compared to a JavaScript program (right) which does the same thing. I would like to save larger images of this but I'm currently unable.

Please make some way to at least take screenshots of the current screen. Ideally the ability to take screenshots (and at custom scales and with/without the names and path names on things) is preferable.

**Comment by BFergerson** [comment]
I was going to make a feature request for the ability to restore a previously constructed representation but this ticket popped up instead. This ticket is not exactly the same type of feature request but could probably be lumped in.

Basically, I wanted to be able to create a graph in the Workbase and then save that state. The node positions and color and everything. That way I could come back to it and interact with it again. It's like saving but instead of an image, it would be the exact interactable representation it was when you saved it.

**Comment by alexjpwalker** [comment]
Hmm, I think it makes sense to make this be a part of:
- #429 
- #430 

We need to revisit this on implementing workspace state persistence - I'll add a note to these issues.

**Comment by james-whiteside** [comment]
This was implemented in Workbase (a long time ago).
