### ISSUE TITLE
Off-Screen Window

### ISSUE THREAD

**Issue by raven44099** [vaticle/typedb-studio#691]
Please replace every line in curly brackets ( { like this } ) with appropriate answers, and remove this line.

## Description

When I follow the tutorial on https://docs.vaticle.com/docs/studio/quickstart,
I click on the "Connect to TypeDB", then the window appears almost out of my display, as can be seen in the picture below:

![image](https://user-images.githubusercontent.com/67215370/209617222-d8f07efc-6e38-4ec7-baf0-a2f0a63ce5f8.png)
This is suboptimal, but it gets worse when I click on "Open Project": The new window opens somewhere where I cannot see it at all. Further, any click in the TypeDB Studio GUI is unabled, thereby showing that the winow is effectively opened.

I worked around this by unplugging my second monitor (HDMI). This is the window that I am talking about:
![image](https://user-images.githubusercontent.com/67215370/209618530-8f55fac0-4065-4747-ab12-ff795ee9dc45.png)

## Environment

1. TypeDB version: TypeDB 2.14.2 
2. OS of TypeDB server: Windows 10
3. Studio version: 2.14.2 (according to https://vaticle.com/download#typedb-studio )
4. OS of Studio: Windows 10
5. Other environment details: None

**Comment by jamesreprise** [comment]
Hi @raven44099, 

This will be fixed in the next release. I'll tag you here once it's out.

See: https://github.com/vaticle/typedb-studio/issues/613
