### ISSUE TITLE
UI Scaling on wayland with 4k monitor messed up

### ISSUE THREAD

**Issue by MTRNord** [vaticle/typedb-studio#697]
## Description

Hi I have a 4k and a 1080p monitor and run wayland kde. On both monitors the UI is TINY with no obvious way to adjust this. The 4k Monitor is on the system scaled to 200% while the other monitor is at 100%. The system has xwayland available too.

![image](https://user-images.githubusercontent.com/1374914/212989628-54074ac0-cff9-4e5d-8554-9b6e8fee0304.png)

## Environment

1. TypeDB version: TypeDB Studio 2.14.2
2. OS of TypeDB server: Fedora Kinoite
3. Studio version: 2.14.2
4. OS of Studio: Fedora Kinoite
5. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Simply opening this on the setup mentioned in the description results in this. Not sure if this is reproducible in another setup or if this is due to  the 4k monitor as my primary

## Expected Output

The UI should scale according to the current monitor size as well as the scaling from the system.

## Actual Output

The UI is so tiny that I cant even read any buttons

**Comment by alexjpwalker** [comment]
Thanks for the report @MTRNord !

Related:
- https://github.com/vaticle/typedb-studio/issues/600

Worth considering: set the font size (which should also scale the overall UI) based on the monitor's resolution on first startup.

**Comment by alexjpwalker** [comment]
I've updated the linked issue to include notes on:

- Ensuring the whole UI is scaled when the font size is scaled;
- Auto-configuring the default font size / UI scaling on first startup based on the monitor's resolution and pixel density.

Closing this issue as duplicate as it is now entirely covered by the linked issue.

**Comment by MTRNord** [comment]
> Thanks for the report @MTRNord !
> 
> Related:
> - https://github.com/vaticle/typedb-studio/issues/600
> 
> Worth considering: set the font size (which should also scale the overall UI) based on the monitor's resolution on first startup.

A sorry I wasn't able to find that issue using the github search. That seems like the same issue. Currently without ui scaling the software is sadly unusable for me :/
