### ISSUE TITLE
The Graph which is getting while writing the query in TypeDB Studio, I just want that in an .pdf, .exe, etc. format. Just because I don't want the user to download and write queries for future.

### ISSUE THREAD

**Issue by Chirag881** [vaticle/typedb-studio#704]
Please replace every line in curly brackets ( { like this } ) with appropriate answers, and remove this line.

## Problem to Solve

{ Please describe the problem you would like to solve. }

## Current Workaround

{ Please describe how you currently solve or work around this problem, given TypeDB's limitation. }

## Proposed Solution

{ Please describe the solution you would like TypeDB to provide, to solve the problem above. }

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by jamesreprise** [comment]
Merged into https://github.com/vaticle/typedb-studio/issues/684.
