### ISSUE TITLE
Double click does not always register

### ISSUE THREAD

**Issue by james-whiteside** [vaticle/typedb-studio#716]
## Description

One user has reported that their double click did not always register when using it to do certain actions like opening tabs from the Project or Type windows by double-clicking them.

## Environment

1. TypeDB version: 2.15.0
2. OS of TypeDB server: MacOS
3. Studio version: 2.14.2
4. OS of Studio: MacOS

## Reproducible Steps

Open a project and create some types then use a double click on project files or types in their respective windows to open them as tabs.

## Expected Output

Target tab is opened in the main window.

## Actual Output

Target tab does not open.

## Additional information

Reported by a TypeDB Academy March 2023 participant.

**Comment by izmalk** [comment]
I think that might be caused by the https://github.com/vaticle/typedb-studio/issues/757
