### ISSUE TITLE
Make sure to always close session / transaction using try / finally in tests

### ISSUE THREAD

**Issue by lolski** [vaticle/typedb-studio#74]
We've seen issues where tests (e.g, in SchemaHandlerTest.js) would hang when fail, such as here: https://circleci.com/gh/Irtazaraza/workbase/72

The issue is caused by the fact that connections aren't properly terminated when the test throws an exception. The solution is to always use `try`/`finally` block.

From
```
tx = ...
expect(...) // may throw
tx.close()
```

To
```
tx = ...
try {
  expect(...) // may throw
}
finally {
  tx.close() // ensure tx.close() is always close
}
```

**Comment by alexjpwalker** [comment]
This issue is no longer relevant in Studio (because we don't have any tests :) )
