### ISSUE TITLE
Explained concepts appear in the wrong place on the graph visualisation

### ISSUE THREAD

**Issue by james-whiteside** [vaticle/typedb-studio#759]
## Description

Currently, concepts spawned by explanations appear at (I think) the coordinate origin. This means that, if something is explained away from the origin, the explanation appears in the wrong part of the graph, creating very long edges and becoming tangled with concepts already in that area. This makes demos involving a lot of explanations difficult to run neatly. Concepts spawned by explanations should appear close to the concept being explained.

**Comment by alexjpwalker** [comment]
Duplicates #561
