### ISSUE TITLE
Fix release pipeline of Workbase due to missing distribution files

### ISSUE THREAD

**Issue by lolski** [vaticle/typedb-studio#85]
## Description

Attempting to release a Github draft from the `release-github-draft` job in CircleCI will fail.

## Environment
1. Workbase's `release-github-draft` CircleCI job

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Approve a release from grabl.grakn.ai

## Expected Output

A Github draft is created, containing Workbase distribution for mac, linux, and windows.

## Actual Output

The `release-github-draft` job will fail with the following error:

```
# the following excerpt is taken from https://circleci.com/gh/graknlabs/workbase/714

cat: can't open 'VERSION': No such file or directory
Failed to find assets from ./artifacts: failed to get file stat: stat /root/grakn/artifacts: no such file or directory
```

**Comment by alexjpwalker** [comment]
The release pipeline is all working now in Studio.
